version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_v1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nestdb
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: nestpassword
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  nestjs-app:
    container_name: nestjs_app_v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: nestuser
      DATABASE_PASSWORD: nestpassword
      DATABASE_NAME: nestdb
  #   networks:
  #     - nest-network

volumes:
  mysql-data:

# networks:
#   nest-network:
#     driver: bridge